<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-T5C0I2QV" failures="1" tests="2" name="Test" time="16.114" errors="0" timestamp="24 Jul 2020 04:27:52 GMT">
  <testcase classname="Demo.FirstTest" name="validedErrorMasage" time="0.929">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Demo.FirstTest.validedErrorMasage(FirstTest.java:40)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- validedErrorMasage -->
  <testcase classname="Demo.UnitTest" name="test1" time="8.295"/>
</testsuite> <!-- Test -->
